### ISSUE TITLE
Auto-generate the catalog file 

### ISSUE THREAD

**Issue by S2Ola** [EBISPOT/scatlas_ontology#5]
Create an autogenerate catalog file to auto populate new import ontologies details to the  catalog file.

**Comment by matentzn** [comment]
Try this: 

1) In your scatlas-odk.yaml, add a new section:
```
components:
  products:
    - filename: fbbt.owl
    - filename: cl.owl
```
See [here](https://github.com/INCATools/ontology-development-kit/blob/master/configs/wbphenotype-odk.yaml) for an example.

2) run the sh upgrage_SCAtlas.sh script
3) Open odk/target/scatlas/src/ontology/catalog-001.xml in atom. What does it contain?
4) What does odk/target/scatlas/src/components contain? fbbt.owl and cl.owl?
